#pragma once

#define AUDIO_REG_ADDRESS_OFFSET 0xFF10
#define AUDIO_REG_SIZE 0x30
#define AUDIO_RAM_ADDRESS_OFFSET 0xFF30
#define AUDIO_RAM_SIZE 0x10
#define AUDIO_NR50_ADDRESS 0xFF24
#define AUDIO_NR51_ADDRESS 0xFF25
#define AUDIO_NR52_ADDRESS 0xFF26
#define AUDIO_CHANNELS_NUM 4
#define AUDIO_CHANNEL_SWEEP_SQUARE 0
#define AUDIO_CHANNEL_SQUARE 1
#define AUDIO_CHANNEL_WAVE 2
#define AUDIO_CHANNEL_NOISE 3
#define AUDIO_CHANNEL_REG_NUM 5
#define AUDIO_CHANNEL_NRX0_ADDRESS 0
#define AUDIO_CHANNEL_NRX1_ADDRESS 1
#define AUDIO_CHANNEL_NRX2_ADDRESS 2
#define AUDIO_CHANNEL_NRX3_ADDRESS 3
#define AUDIO_CHANNEL_NRX4_ADDRESS 4
#define AUDIO_CHANNEL_MODULES_NUM 4
#define AUDIO_CHANNEL1_ENABLE_MASK 0x1
#define AUDIO_CHANNEL2_ENABLE_MASK 0x2
#define AUDIO_CHANNEL3_ENABLE_MASK 0x4
#define AUDIO_CHANNEL4_ENABLE_MASK 0x8
