#pragma once

#define AUDIO_CHANNELS_NUM 4
#define AUDIO_CHANNEL_REG_NUM 5
#define AUDIO_CHANNEL_NRX0_ADDRESS 0
#define AUDIO_CHANNEL_NRX1_ADDRESS 1
#define AUDIO_CHANNEL_NRX2_ADDRESS 2
#define AUDIO_CHANNEL_NRX3_ADDRESS 3
#define AUDIO_CHANNEL_NRX4_ADDRESS 4
#define AUDIO_CHANNEL_MODULES_NUM 4
#define AUDIO_CHANNEL1_ENABLE_MASK 0x1
#define AUDIO_CHANNEL2_ENABLE_MASK 0x2
#define AUDIO_CHANNEL3_ENABLE_MASK 0x4
#define AUDIO_CHANNEL4_ENABLE_MASK 0x8
