#ifndef GBAUDIOCOMMONDEFS_H
#define GBAUDIOCOMMONDEFS_H

#define AUDIO_CHANNEL_REG_NUM 5
#define AUDIO_CHANNEL_NR0_IDX 0
#define AUDIO_CHANNEL_NR1_IDX 0
#define AUDIO_CHANNEL_NR2_IDX 0
#define AUDIO_CHANNEL_NR3_IDX 0
#define AUDIO_CHANNEL_NR4_IDX 0

#endif // GBAUDIOCOMMONDEFS_H
