#include "GBCpu.h"

GBInstruction GBCpu::s_InstructionTable[INSTRUCTIONS_NUM] =
{
    //Regular instruction set
    nullptr,                                        //0x00
    static_cast<GBInstruction>(&GBCpu::LD_rr_nn),   //0x01
    static_cast<GBInstruction>(&GBCpu::LD_addr_A),  //0x02
    static_cast<GBInstruction>(&GBCpu::INC_rr),     //0x03
    static_cast<GBInstruction>(&GBCpu::INC_r),      //0x04
    static_cast<GBInstruction>(&GBCpu::DEC_r),      //0x05
    static_cast<GBInstruction>(&GBCpu::LD_r_n),     //0x06
    nullptr,                                        //0x07
    nullptr,                                        //0x08
    nullptr,                                        //0x09
    static_cast<GBInstruction>(&GBCpu::LD_A_addr),  //0x0A
    nullptr,                                        //0x0B
    static_cast<GBInstruction>(&GBCpu::INC_r),      //0x0C
    static_cast<GBInstruction>(&GBCpu::DEC_r),      //0x0D
    static_cast<GBInstruction>(&GBCpu::LD_r_n),     //0x0E
    nullptr,                                        //0x0F
    nullptr,                                        //0x10
    static_cast<GBInstruction>(&GBCpu::LD_rr_nn),   //0x11
    static_cast<GBInstruction>(&GBCpu::LD_addr_A),  //0x12
    static_cast<GBInstruction>(&GBCpu::INC_rr),     //0x13
    static_cast<GBInstruction>(&GBCpu::INC_r),      //0x14
    static_cast<GBInstruction>(&GBCpu::DEC_r),      //0x15
    static_cast<GBInstruction>(&GBCpu::LD_r_n),     //0x16
    static_cast<GBInstruction>(&GBCpu::RLA),        //0x17
    static_cast<GBInstruction>(&GBCpu::JR),         //0x18
    nullptr,                                        //0x19
    static_cast<GBInstruction>(&GBCpu::LD_A_addr),  //0x1A
    nullptr,                                        //0x1B
    static_cast<GBInstruction>(&GBCpu::INC_r),      //0x1C
    static_cast<GBInstruction>(&GBCpu::DEC_r),      //0x1D
    static_cast<GBInstruction>(&GBCpu::LD_r_n),     //0x1E
    nullptr,                                        //0x1F
    static_cast<GBInstruction>(&GBCpu::JR),         //0x20
    static_cast<GBInstruction>(&GBCpu::LD_rr_nn),   //0x21
    static_cast<GBInstruction>(&GBCpu::LDI),        //0x22
    static_cast<GBInstruction>(&GBCpu::INC_rr),     //0x23
    static_cast<GBInstruction>(&GBCpu::INC_r),      //0x24
    static_cast<GBInstruction>(&GBCpu::DEC_r),      //0x25
    static_cast<GBInstruction>(&GBCpu::LD_r_n),     //0x26
    nullptr,                                        //0x27
    static_cast<GBInstruction>(&GBCpu::JR),         //0x28
    nullptr,                                        //0x29
    static_cast<GBInstruction>(&GBCpu::LDI),        //0x2A
    nullptr,                                        //0x2B
    static_cast<GBInstruction>(&GBCpu::INC_r),      //0x2C
    static_cast<GBInstruction>(&GBCpu::DEC_r),      //0x2D
    static_cast<GBInstruction>(&GBCpu::LD_r_n),     //0x2E
    nullptr,                                        //0x2F
    static_cast<GBInstruction>(&GBCpu::JR),         //0x30
    static_cast<GBInstruction>(&GBCpu::LD_rr_nn),   //0x31
    static_cast<GBInstruction>(&GBCpu::LDD),        //0x32
    static_cast<GBInstruction>(&GBCpu::INC_rr),     //0x33
    static_cast<GBInstruction>(&GBCpu::INC_r),      //0x34
    static_cast<GBInstruction>(&GBCpu::DEC_r),      //0x35
    static_cast<GBInstruction>(&GBCpu::LD_r_n),     //0x36
    nullptr,                                        //0x37
    static_cast<GBInstruction>(&GBCpu::JR),         //0x38
    nullptr,                                        //0x39
    static_cast<GBInstruction>(&GBCpu::LDD),        //0x3A
    nullptr,                                        //0x3B
    static_cast<GBInstruction>(&GBCpu::INC_r),      //0x3C
    static_cast<GBInstruction>(&GBCpu::DEC_r),      //0x3D
    static_cast<GBInstruction>(&GBCpu::LD_r_n),     //0x3E
    nullptr,                                        //0x3F
    static_cast<GBInstruction>(&GBCpu::LD_r1_r2),   //0x40
    static_cast<GBInstruction>(&GBCpu::LD_r1_r2),   //0x41
    static_cast<GBInstruction>(&GBCpu::LD_r1_r2),   //0x42
    static_cast<GBInstruction>(&GBCpu::LD_r1_r2),   //0x43
    static_cast<GBInstruction>(&GBCpu::LD_r1_r2),   //0x44
    static_cast<GBInstruction>(&GBCpu::LD_r1_r2),   //0x45
    static_cast<GBInstruction>(&GBCpu::LD_r1_r2),   //0x46
    static_cast<GBInstruction>(&GBCpu::LD_r1_r2),   //0x47
    static_cast<GBInstruction>(&GBCpu::LD_r1_r2),   //0x48
    static_cast<GBInstruction>(&GBCpu::LD_r1_r2),   //0x49
    static_cast<GBInstruction>(&GBCpu::LD_r1_r2),   //0x4A
    static_cast<GBInstruction>(&GBCpu::LD_r1_r2),   //0x4B
    static_cast<GBInstruction>(&GBCpu::LD_r1_r2),   //0x4C
    static_cast<GBInstruction>(&GBCpu::LD_r1_r2),   //0x4D
    static_cast<GBInstruction>(&GBCpu::LD_r1_r2),   //0x4E
    static_cast<GBInstruction>(&GBCpu::LD_r1_r2),   //0x4F
    static_cast<GBInstruction>(&GBCpu::LD_r1_r2),   //0x50
    static_cast<GBInstruction>(&GBCpu::LD_r1_r2),   //0x51
    static_cast<GBInstruction>(&GBCpu::LD_r1_r2),   //0x52
    static_cast<GBInstruction>(&GBCpu::LD_r1_r2),   //0x53
    static_cast<GBInstruction>(&GBCpu::LD_r1_r2),   //0x54
    static_cast<GBInstruction>(&GBCpu::LD_r1_r2),   //0x55
    static_cast<GBInstruction>(&GBCpu::LD_r1_r2),   //0x56
    static_cast<GBInstruction>(&GBCpu::LD_r1_r2),   //0x57
    static_cast<GBInstruction>(&GBCpu::LD_r1_r2),   //0x58
    static_cast<GBInstruction>(&GBCpu::LD_r1_r2),   //0x59
    static_cast<GBInstruction>(&GBCpu::LD_r1_r2),   //0x5A
    static_cast<GBInstruction>(&GBCpu::LD_r1_r2),   //0x5B
    static_cast<GBInstruction>(&GBCpu::LD_r1_r2),   //0x5C
    static_cast<GBInstruction>(&GBCpu::LD_r1_r2),   //0x5D
    static_cast<GBInstruction>(&GBCpu::LD_r1_r2),   //0x5E
    static_cast<GBInstruction>(&GBCpu::LD_r1_r2),   //0x5F
    static_cast<GBInstruction>(&GBCpu::LD_r1_r2),   //0x60
    static_cast<GBInstruction>(&GBCpu::LD_r1_r2),   //0x61
    static_cast<GBInstruction>(&GBCpu::LD_r1_r2),   //0x62
    static_cast<GBInstruction>(&GBCpu::LD_r1_r2),   //0x63
    static_cast<GBInstruction>(&GBCpu::LD_r1_r2),   //0x64
    static_cast<GBInstruction>(&GBCpu::LD_r1_r2),   //0x65
    static_cast<GBInstruction>(&GBCpu::LD_r1_r2),   //0x66
    static_cast<GBInstruction>(&GBCpu::LD_r1_r2),   //0x67
    static_cast<GBInstruction>(&GBCpu::LD_r1_r2),   //0x68
    static_cast<GBInstruction>(&GBCpu::LD_r1_r2),   //0x69
    static_cast<GBInstruction>(&GBCpu::LD_r1_r2),   //0x6A
    static_cast<GBInstruction>(&GBCpu::LD_r1_r2),   //0x6B
    static_cast<GBInstruction>(&GBCpu::LD_r1_r2),   //0x6C
    static_cast<GBInstruction>(&GBCpu::LD_r1_r2),   //0x6D
    static_cast<GBInstruction>(&GBCpu::LD_r1_r2),   //0x6E
    static_cast<GBInstruction>(&GBCpu::LD_r1_r2),   //0x6F
    static_cast<GBInstruction>(&GBCpu::LD_r1_r2),   //0x70
    static_cast<GBInstruction>(&GBCpu::LD_r1_r2),   //0x71
    static_cast<GBInstruction>(&GBCpu::LD_r1_r2),   //0x72
    static_cast<GBInstruction>(&GBCpu::LD_r1_r2),   //0x73
    static_cast<GBInstruction>(&GBCpu::LD_r1_r2),   //0x74
    static_cast<GBInstruction>(&GBCpu::LD_r1_r2),   //0x75
    nullptr,                                        //0x76
    static_cast<GBInstruction>(&GBCpu::LD_r1_r2),   //0x77
    static_cast<GBInstruction>(&GBCpu::LD_r1_r2),   //0x78
    static_cast<GBInstruction>(&GBCpu::LD_r1_r2),   //0x79
    static_cast<GBInstruction>(&GBCpu::LD_r1_r2),   //0x7A
    static_cast<GBInstruction>(&GBCpu::LD_r1_r2),   //0x7B
    static_cast<GBInstruction>(&GBCpu::LD_r1_r2),   //0x7C
    static_cast<GBInstruction>(&GBCpu::LD_r1_r2),   //0x7D
    static_cast<GBInstruction>(&GBCpu::LD_r1_r2),   //0x7E
    static_cast<GBInstruction>(&GBCpu::LD_r1_r2),   //0x7F
    static_cast<GBInstruction>(&GBCpu::ADD),        //0x80
    static_cast<GBInstruction>(&GBCpu::ADD),        //0x81
    static_cast<GBInstruction>(&GBCpu::ADD),        //0x82
    static_cast<GBInstruction>(&GBCpu::ADD),        //0x83
    static_cast<GBInstruction>(&GBCpu::ADD),        //0x84
    static_cast<GBInstruction>(&GBCpu::ADD),        //0x85
    static_cast<GBInstruction>(&GBCpu::ADD),        //0x86
    static_cast<GBInstruction>(&GBCpu::ADD),        //0x87
    nullptr,                                        //0x88
    nullptr,                                        //0x89
    nullptr,                                        //0x8A
    nullptr,                                        //0x8B
    nullptr,                                        //0x8C
    nullptr,                                        //0x8D
    nullptr,                                        //0x8E
    nullptr,                                        //0x8F
    static_cast<GBInstruction>(&GBCpu::SUB),        //0x90
    static_cast<GBInstruction>(&GBCpu::SUB),        //0x91
    static_cast<GBInstruction>(&GBCpu::SUB),        //0x92
    static_cast<GBInstruction>(&GBCpu::SUB),        //0x93
    static_cast<GBInstruction>(&GBCpu::SUB),        //0x94
    static_cast<GBInstruction>(&GBCpu::SUB),        //0x95
    static_cast<GBInstruction>(&GBCpu::SUB),        //0x96
    static_cast<GBInstruction>(&GBCpu::SUB),        //0x97
    nullptr,                                        //0x98
    nullptr,                                        //0x99
    nullptr,                                        //0x9A
    nullptr,                                        //0x9B
    nullptr,                                        //0x9C
    nullptr,                                        //0x9D
    nullptr,                                        //0x9E
    nullptr,                                        //0x9F
    nullptr,                                        //0xA0
    nullptr,                                        //0xA1
    nullptr,                                        //0xA2
    nullptr,                                        //0xA3
    nullptr,                                        //0xA4
    nullptr,                                        //0xA5
    nullptr,                                        //0xA6
    nullptr,                                        //0xA7
    static_cast<GBInstruction>(&GBCpu::XOR),        //0xA8
    static_cast<GBInstruction>(&GBCpu::XOR),        //0xA9
    static_cast<GBInstruction>(&GBCpu::XOR),        //0xAA
    static_cast<GBInstruction>(&GBCpu::XOR),        //0xAB
    static_cast<GBInstruction>(&GBCpu::XOR),        //0xAC
    static_cast<GBInstruction>(&GBCpu::XOR),        //0xAD
    static_cast<GBInstruction>(&GBCpu::XOR),        //0xAE
    static_cast<GBInstruction>(&GBCpu::XOR),        //0xAF
    nullptr,                                        //0xB0
    nullptr,                                        //0xB1
    nullptr,                                        //0xB2
    nullptr,                                        //0xB3
    nullptr,                                        //0xB4
    nullptr,                                        //0xB5
    nullptr,                                        //0xB6
    nullptr,                                        //0xB7
    static_cast<GBInstruction>(&GBCpu::CP),         //0xB8
    static_cast<GBInstruction>(&GBCpu::CP),         //0xB9
    static_cast<GBInstruction>(&GBCpu::CP),         //0xBA
    static_cast<GBInstruction>(&GBCpu::CP),         //0xBB
    static_cast<GBInstruction>(&GBCpu::CP),         //0xBC
    static_cast<GBInstruction>(&GBCpu::CP),         //0xBD
    static_cast<GBInstruction>(&GBCpu::CP),         //0xBE
    static_cast<GBInstruction>(&GBCpu::CP),         //0xBF
    static_cast<GBInstruction>(&GBCpu::RET),        //0xC0
    static_cast<GBInstruction>(&GBCpu::POP),        //0xC1
    nullptr,                                        //0xC2
    nullptr,                                        //0xC3
    static_cast<GBInstruction>(&GBCpu::CALL),       //0xC4
    static_cast<GBInstruction>(&GBCpu::PUSH),       //0xC5
    static_cast<GBInstruction>(&GBCpu::ADD),        //0xC6
    nullptr,                                        //0xC7
    static_cast<GBInstruction>(&GBCpu::RET),        //0xC8
    static_cast<GBInstruction>(&GBCpu::RET),        //0xC9
    nullptr,                                        //0xCA
    nullptr,                                        //0xCB
    static_cast<GBInstruction>(&GBCpu::CALL),       //0xCC
    static_cast<GBInstruction>(&GBCpu::CALL),       //0xCD
    nullptr,                                        //0xCE
    nullptr,                                        //0xCF
    static_cast<GBInstruction>(&GBCpu::RET),        //0xD0
    static_cast<GBInstruction>(&GBCpu::POP),        //0xD1
    nullptr,                                        //0xD2
    nullptr,                                        //0xD3
    static_cast<GBInstruction>(&GBCpu::CALL),       //0xD4
    static_cast<GBInstruction>(&GBCpu::PUSH),       //0xD5
    static_cast<GBInstruction>(&GBCpu::SUB),        //0xD6
    nullptr,                                        //0xD7
    static_cast<GBInstruction>(&GBCpu::RET),        //0xD8
    nullptr,                                        //0xD9
    nullptr,                                        //0xDA
    nullptr,                                        //0xDB
    static_cast<GBInstruction>(&GBCpu::CALL),       //0xDC
    nullptr,                                        //0xDD
    nullptr,                                        //0xDE
    nullptr,                                        //0xDF
    static_cast<GBInstruction>(&GBCpu::LD_off_A),   //0xE0
    static_cast<GBInstruction>(&GBCpu::POP),        //0xE1
    static_cast<GBInstruction>(&GBCpu::LD_off_A),   //0xE2
    nullptr,                                        //0xE3
    nullptr,                                        //0xE4
    static_cast<GBInstruction>(&GBCpu::PUSH),       //0xE5
    nullptr,                                        //0xE6
    nullptr,                                        //0xE7
    nullptr,                                        //0xE8
    nullptr,                                        //0xE9
    static_cast<GBInstruction>(&GBCpu::LD_addr_A),  //0xEA
    nullptr,                                        //0xEB
    nullptr,                                        //0xEC
    nullptr,                                        //0xED
    static_cast<GBInstruction>(&GBCpu::XOR),        //0xEE
    nullptr,                                        //0xEF
    static_cast<GBInstruction>(&GBCpu::LD_A_off),   //0xF0
    static_cast<GBInstruction>(&GBCpu::POP),        //0xF1
    static_cast<GBInstruction>(&GBCpu::LD_A_off),   //0xF2
    nullptr,                                        //0xF3
    nullptr,                                        //0xF4
    static_cast<GBInstruction>(&GBCpu::PUSH),       //0xF5
    nullptr,                                        //0xF6
    nullptr,                                        //0xF7
    nullptr,                                        //0xF8
    nullptr,                                        //0xF9
    static_cast<GBInstruction>(&GBCpu::LD_A_addr),  //0xFA
    nullptr,                                        //0xFB
    nullptr,                                        //0xFC
    nullptr,                                        //0xFD
    static_cast<GBInstruction>(&GBCpu::CP),         //0xFE
    nullptr,                                        //0xFF
};

GBInstruction GBCpu::s_CBInstructionTable[INSTRUCTIONS_NUM] =
{
    //Regular instruction set
    nullptr,                                        //0x00
    nullptr,                                        //0x01
    nullptr,                                        //0x02
    nullptr,                                        //0x03
    nullptr,                                        //0x04
    nullptr,                                        //0x05
    nullptr,                                        //0x06
    nullptr,                                        //0x07
    nullptr,                                        //0x08
    nullptr,                                        //0x09
    nullptr,                                        //0x0A
    nullptr,                                        //0x0B
    nullptr,                                        //0x0C
    nullptr,                                        //0x0D
    nullptr,                                        //0x0E
    nullptr,                                        //0x0F
    static_cast<GBInstruction>(&GBCpu::RL),         //0x10
    static_cast<GBInstruction>(&GBCpu::RL),         //0x11
    static_cast<GBInstruction>(&GBCpu::RL),         //0x12
    static_cast<GBInstruction>(&GBCpu::RL),         //0x13
    static_cast<GBInstruction>(&GBCpu::RL),         //0x14
    static_cast<GBInstruction>(&GBCpu::RL),         //0x15
    static_cast<GBInstruction>(&GBCpu::RL),         //0x16
    static_cast<GBInstruction>(&GBCpu::RL),         //0x17
    nullptr,                                        //0x18
    nullptr,                                        //0x19
    nullptr,                                        //0x1A
    nullptr,                                        //0x1B
    nullptr,                                        //0x1C
    nullptr,                                        //0x1D
    nullptr,                                        //0x1E
    nullptr,                                        //0x1F
    nullptr,                                        //0x20
    nullptr,                                        //0x21
    nullptr,                                        //0x22
    nullptr,                                        //0x23
    nullptr,                                        //0x24
    nullptr,                                        //0x25
    nullptr,                                        //0x26
    nullptr,                                        //0x27
    nullptr,                                        //0x28
    nullptr,                                        //0x29
    nullptr,                                        //0x2A
    nullptr,                                        //0x2B
    nullptr,                                        //0x2C
    nullptr,                                        //0x2D
    nullptr,                                        //0x2E
    nullptr,                                        //0x2F
    nullptr,                                        //0x30
    nullptr,                                        //0x31
    nullptr,                                        //0x32
    nullptr,                                        //0x33
    nullptr,                                        //0x34
    nullptr,                                        //0x35
    nullptr,                                        //0x36
    nullptr,                                        //0x37
    nullptr,                                        //0x38
    nullptr,                                        //0x39
    nullptr,                                        //0x3A
    nullptr,                                        //0x3B
    nullptr,                                        //0x3C
    nullptr,                                        //0x3D
    nullptr,                                        //0x3E
    nullptr,                                        //0x3F
    static_cast<GBInstruction>(&GBCpu::BIT),        //0x40
    static_cast<GBInstruction>(&GBCpu::BIT),        //0x41
    static_cast<GBInstruction>(&GBCpu::BIT),        //0x42
    static_cast<GBInstruction>(&GBCpu::BIT),        //0x43
    static_cast<GBInstruction>(&GBCpu::BIT),        //0x44
    static_cast<GBInstruction>(&GBCpu::BIT),        //0x45
    static_cast<GBInstruction>(&GBCpu::BIT),        //0x46
    static_cast<GBInstruction>(&GBCpu::BIT),        //0x47
    static_cast<GBInstruction>(&GBCpu::BIT),        //0x48
    static_cast<GBInstruction>(&GBCpu::BIT),        //0x49
    static_cast<GBInstruction>(&GBCpu::BIT),        //0x4A
    static_cast<GBInstruction>(&GBCpu::BIT),        //0x4B
    static_cast<GBInstruction>(&GBCpu::BIT),        //0x4C
    static_cast<GBInstruction>(&GBCpu::BIT),        //0x4D
    static_cast<GBInstruction>(&GBCpu::BIT),        //0x4E
    static_cast<GBInstruction>(&GBCpu::BIT),        //0x4F
    static_cast<GBInstruction>(&GBCpu::BIT),        //0x50
    static_cast<GBInstruction>(&GBCpu::BIT),        //0x51
    static_cast<GBInstruction>(&GBCpu::BIT),        //0x52
    static_cast<GBInstruction>(&GBCpu::BIT),        //0x53
    static_cast<GBInstruction>(&GBCpu::BIT),        //0x54
    static_cast<GBInstruction>(&GBCpu::BIT),        //0x55
    static_cast<GBInstruction>(&GBCpu::BIT),        //0x56
    static_cast<GBInstruction>(&GBCpu::BIT),        //0x57
    static_cast<GBInstruction>(&GBCpu::BIT),        //0x58
    static_cast<GBInstruction>(&GBCpu::BIT),        //0x59
    static_cast<GBInstruction>(&GBCpu::BIT),        //0x5A
    static_cast<GBInstruction>(&GBCpu::BIT),        //0x5B
    static_cast<GBInstruction>(&GBCpu::BIT),        //0x5C
    static_cast<GBInstruction>(&GBCpu::BIT),        //0x5D
    static_cast<GBInstruction>(&GBCpu::BIT),        //0x5E
    static_cast<GBInstruction>(&GBCpu::BIT),        //0x5F
    static_cast<GBInstruction>(&GBCpu::BIT),        //0x60
    static_cast<GBInstruction>(&GBCpu::BIT),        //0x61
    static_cast<GBInstruction>(&GBCpu::BIT),        //0x62
    static_cast<GBInstruction>(&GBCpu::BIT),        //0x63
    static_cast<GBInstruction>(&GBCpu::BIT),        //0x64
    static_cast<GBInstruction>(&GBCpu::BIT),        //0x65
    static_cast<GBInstruction>(&GBCpu::BIT),        //0x66
    static_cast<GBInstruction>(&GBCpu::BIT),        //0x67
    static_cast<GBInstruction>(&GBCpu::BIT),        //0x68
    static_cast<GBInstruction>(&GBCpu::BIT),        //0x69
    static_cast<GBInstruction>(&GBCpu::BIT),        //0x6A
    static_cast<GBInstruction>(&GBCpu::BIT),        //0x6B
    static_cast<GBInstruction>(&GBCpu::BIT),        //0x6C
    static_cast<GBInstruction>(&GBCpu::BIT),        //0x6D
    static_cast<GBInstruction>(&GBCpu::BIT),        //0x6E
    static_cast<GBInstruction>(&GBCpu::BIT),        //0x6F
    static_cast<GBInstruction>(&GBCpu::BIT),        //0x70
    static_cast<GBInstruction>(&GBCpu::BIT),        //0x71
    static_cast<GBInstruction>(&GBCpu::BIT),        //0x72
    static_cast<GBInstruction>(&GBCpu::BIT),        //0x73
    static_cast<GBInstruction>(&GBCpu::BIT),        //0x74
    static_cast<GBInstruction>(&GBCpu::BIT),        //0x75
    static_cast<GBInstruction>(&GBCpu::BIT),        //0x76
    static_cast<GBInstruction>(&GBCpu::BIT),        //0x77
    static_cast<GBInstruction>(&GBCpu::BIT),        //0x78
    static_cast<GBInstruction>(&GBCpu::BIT),        //0x79
    static_cast<GBInstruction>(&GBCpu::BIT),        //0x7A
    static_cast<GBInstruction>(&GBCpu::BIT),        //0x7B
    static_cast<GBInstruction>(&GBCpu::BIT),        //0x7C
    static_cast<GBInstruction>(&GBCpu::BIT),        //0x7D
    static_cast<GBInstruction>(&GBCpu::BIT),        //0x7E
    static_cast<GBInstruction>(&GBCpu::BIT),        //0x7F
    nullptr,                                        //0x80
    nullptr,                                        //0x81
    nullptr,                                        //0x82
    nullptr,                                        //0x83
    nullptr,                                        //0x84
    nullptr,                                        //0x85
    nullptr,                                        //0x86
    nullptr,                                        //0x87
    nullptr,                                        //0x88
    nullptr,                                        //0x89
    nullptr,                                        //0x8A
    nullptr,                                        //0x8B
    nullptr,                                        //0x8C
    nullptr,                                        //0x8D
    nullptr,                                        //0x8E
    nullptr,                                        //0x8F
    nullptr,                                        //0x90
    nullptr,                                        //0x91
    nullptr,                                        //0x92
    nullptr,                                        //0x93
    nullptr,                                        //0x94
    nullptr,                                        //0x95
    nullptr,                                        //0x96
    nullptr,                                        //0x97
    nullptr,                                        //0x98
    nullptr,                                        //0x99
    nullptr,                                        //0x9A
    nullptr,                                        //0x9B
    nullptr,                                        //0x9C
    nullptr,                                        //0x9D
    nullptr,                                        //0x9E
    nullptr,                                        //0x9F
    nullptr,                                        //0xA0
    nullptr,                                        //0xA1
    nullptr,                                        //0xA2
    nullptr,                                        //0xA3
    nullptr,                                        //0xA4
    nullptr,                                        //0xA5
    nullptr,                                        //0xA6
    nullptr,                                        //0xA7
    nullptr,                                        //0xA8
    nullptr,                                        //0xA9
    nullptr,                                        //0xAA
    nullptr,                                        //0xAB
    nullptr,                                        //0xAC
    nullptr,                                        //0xAD
    nullptr,                                        //0xAE
    nullptr,                                        //0xAF
    nullptr,                                        //0xB0
    nullptr,                                        //0xB1
    nullptr,                                        //0xB2
    nullptr,                                        //0xB3
    nullptr,                                        //0xB4
    nullptr,                                        //0xB5
    nullptr,                                        //0xB6
    nullptr,                                        //0xB7
    nullptr,                                        //0xB8
    nullptr,                                        //0xB9
    nullptr,                                        //0xBA
    nullptr,                                        //0xBB
    nullptr,                                        //0xBC
    nullptr,                                        //0xBD
    nullptr,                                        //0xBE
    nullptr,                                        //0xBF
    nullptr,                                        //0xC0
    nullptr,                                        //0xC1
    nullptr,                                        //0xC2
    nullptr,                                        //0xC3
    nullptr,                                        //0xC4
    nullptr,                                        //0xC5
    nullptr,                                        //0xC6
    nullptr,                                        //0xC7
    nullptr,                                        //0xC8
    nullptr,                                        //0xC9
    nullptr,                                        //0xCA
    nullptr,                                        //0xCB
    nullptr,                                        //0xCC
    nullptr,                                        //0xCD
    nullptr,                                        //0xCE
    nullptr,                                        //0xCF
    nullptr,                                        //0xD0
    nullptr,                                        //0xD1
    nullptr,                                        //0xD2
    nullptr,                                        //0xD3
    nullptr,                                        //0xD4
    nullptr,                                        //0xD5
    nullptr,                                        //0xD6
    nullptr,                                        //0xD7
    nullptr,                                        //0xD8
    nullptr,                                        //0xD9
    nullptr,                                        //0xDA
    nullptr,                                        //0xDB
    nullptr,                                        //0xDC
    nullptr,                                        //0xDD
    nullptr,                                        //0xDE
    nullptr,                                        //0xDF
    nullptr,                                        //0xE0
    nullptr,                                        //0xE1
    nullptr,                                        //0xE2
    nullptr,                                        //0xE3
    nullptr,                                        //0xE4
    nullptr,                                        //0xE5
    nullptr,                                        //0xE6
    nullptr,                                        //0xE7
    nullptr,                                        //0xE8
    nullptr,                                        //0xE9
    nullptr,                                        //0xEA
    nullptr,                                        //0xEB
    nullptr,                                        //0xEC
    nullptr,                                        //0xED
    nullptr,                                        //0xEE
    nullptr,                                        //0xEF
    nullptr,                                        //0xF0
    nullptr,                                        //0xF1
    nullptr,                                        //0xF2
    nullptr,                                        //0xF3
    nullptr,                                        //0xF4
    nullptr,                                        //0xF5
    nullptr,                                        //0xF6
    nullptr,                                        //0xF7
    nullptr,                                        //0xF8
    nullptr,                                        //0xF9
    nullptr,                                        //0xFA
    nullptr,                                        //0xFB
    nullptr,                                        //0xFC
    nullptr,                                        //0xFD
    nullptr,                                        //0xFE
    nullptr,                                        //0xFF
};
